= C. Система счисления

Программист Марат совсем недавно начал изучать информатику в Яндекс Учебнике.
Его настолько увлекла тема «Системы счисления»,
что он всю ночь решал примеры на сложение и вычитание чисел в различных системах счисления.
Однако когда на следующий день он снова открыл свои записи, он заметил,
что многие записанные им равенства неверны в тех системах счисления,
которые были даны в примерах из учебника.
«Интересно, а есть ли в принципе какая-то система счисления,
в которой это равенство оказалось бы верным?» — огорчённо спрашивал себя Марат,
глядя в свою тетрадь с примерами.
«А если есть, то какое минимальное у неё может быть основание?» — задумался он.

Помогите Марату ответить на эти вопросы.
Для заданного равенства найдите минимальное основание системы счисления,
в которой равенство будет верным, или укажите, что такой системы счисления нет.

== Формат ввода
В единственной строке s задано арифметическое выражение,
систему счисления которого необходимо определить (|s|<=1000000).

Строка s состоит из цифр 0–9, букв латинского алфавита в верхнем регистре A–Z,
пробелов и символов +, -, =.
Пробелы опциональны и не несут смысла,
они могут отделять арифметические знаки от чисел.

Гарантируется, что s представляет собой синтаксически корректное выражение,
в котором есть ровно один знак = и отсутствуют унарные плюсы и минусы.

== Формат вывода
Выведите минимальное основание b (b≥2) системы счисления,
в которой выражение обращается в верное равенство.
Если такого b нет, выведите −1.

== Пример

[cols=2]
|====
|Ввод
|Вывод

|2 + 2 = 11 - 1
|4

|1 = 1
|2

|2 = 3
|-1

|B = A + 1
|12
|====