= B. Необычное деление

Второклассник Вася учится делить числа.
Пока ему объяснили только деление на числа от 1 до 9.
Вася слушал учительницу невнимательно,
поэтому делит число a на число b следующим образом:
проходит по всем цифрам в числе a,
каждую цифру делит на b,
частное записывает к итоговому числу, а остаток отбрасывает.

К примеру, в Васином делении 36:3=12, поскольку stem:[\frac{3}{3}=1],
stem:[\frac{6}{3}=2].
Но 26:3=02=2, поскольку
stem:[\frac{2}{3}=0].

Чтобы закрепить навык деления, учительница дала ему t домашних работ.
В i-й домашней работе нужно было посчитать
stem:[\frac{1}{b_i}],
stem:[\frac{2}{b_i}],
…,
stem:[\frac{n}{b_i}].

Каждую домашнюю работу учительница оценивает исходя из количества правильно решенных примеров.
Пример считается верным тогда и только тогда,
когда результат Васиного деления a на b совпадает с результатом настоящего деления
a на b без округлений.
Помогите учительнице посчитать, сколько примеров Вася решил верно.

== Формат ввода
Первая строка содержит одно целое положительное число t (1≤t≤10^5^) — количество домашних работ.
Следующие t строк содержат по два целых положительных числа n~i~ (1≤n~i~≤10^18^)
и b~i~ (1≤b~i~≤9) — количество примеров и делитель во всех примерах соответственно.

== Формат вывода
Нужно вывести t строк — количество правильно решенных примеров в каждой домашней работе.

== Пример

[cols=2]
|====
|Ввод
|Вывод

|4 +
10 1 +
36 3 +
11 2 +
1000000000000000000 7
|10 +
6 +
4 +
262143

|====