= D. Релизный менеджер

Вам предстоит написать симулятор релизных пайплайнов.

Дано s сервисов и общий репозиторий с их кодом, в котором d директорий, пронумерованных от 1 до d.

Про каждый коммит известны:

. t — timestamp коммита (в секундах);
. Dc — список номеров затрагиваемых директорий.

Про каждый сервис известны:

. Ds — список номеров директорий, от которых данный сервис зависит;
. n — размер релизной пачки, то есть количество коммитов в зависимости данного сервиса, после которого мгновенно автоматически запускается деплой в продакше;
. rt — длительность релиза для этого сервиса (в секундах).

Процесс релиза сервиса устроен следующим образом: как только набирается n коммитов, затрагивающих директории из списка Ds, этот сервис встает в очередь на релиз. В сервис может идти одновременно только один релиз. Поэтому вначале ожидается завершение активного релиза в сервис (если таковой имеется). Сразу после завершения активного релиза начинается новый релиз того же сервиса. В релиз попадают все коммиты, которые были в репозитории на момент старта.

Вам даны лог коммитов и набор запросов. В ответ на запрос нужно вывести информацию о том, когда данный коммит впервые окажется в продакшене сервиса, или -1, если это определить нельзя.

== Формат ввода

Первая строка содержит два натуральных числа d — размер репозитория (d ≤ 1000) и s — количество сервисов (s ≤ 1000).

Далее идёт блок из s строк, i-ая строка в этом блоке описывает i-ый сервис. В начале строки указаны натуральные числа n — размер релизной пачки (n ≤ 10^4^), rt — длительность релиза (rt ≤ 10^4^) и |Ds| — количество директорий, от которых сервис зависит (|Ds| ≤ 100). Затем в той же строке приведены |Ds| различных натуральных чисел, составляющих список Ds.

В следующей строке задано натуральное число c — количество коммитов (c ≤ 10^4^).

Далее идёт блок из c строк, j-ая строка в этом блоке описывает j-ый коммит. В начале строки указаны натуральные числа t — timestamp коммита (t ≤ 10^7^), |Dc| — количество затронутых директорий (|Dc| ≤ d). Затем в той же строке приведены |Dc| различных натуральных чисел, составляющих список Dc. Данные c строк отсортированы в порядке возрастания t, и значение t для каждого коммита уникально. Сумма |Dc| по всем коммитам не превосходит 10^6^.

В следующей строке задано натуральное число q — количество запросов (q ≤ 10^5^).

Далее идёт блок из q строк, k-ая строка в этом блоке описывает k-ый запрос. Запрос содержит два натуральных числа — j (номер коммита) и i (номер сервиса).

Все числа в строках указаны через пробел.

== Формат вывода

Нужно вывести q строк. В k-ой строке нужно указать время, когда коммит из k-го запроса попадёт в продакшен сервиса из k-го запроса, или вывести -1, если это невозможно установить.

== Пример

[cols=2]
|====
|Ввод
|Вывод

|5 3 +
2 150 2 1 2 +
3 100 3 2 3 4 +
1 150 1 4 +
3 +
5 1 2 +
10 1 1 +
13 3 2 3 4 +
3 +
1 1 +
1 2 +
1 3
|160 +
-1 +
163

|3 1 +
2 10 2 1 2 +
6 +
2 2 1 2 +
4 1 3 +
5 1 1 +
8 1 2 +
15 1 1 +
20 1 3 +
3 +
3 1 +
4 1 +
5 1
|15 +
25 +
25
|====