= B. Многомерные коробки

Совсем недавно Яндекс Маркет объявил о расширении зоны доставки за пределы Солнечной системы.
Яндексоиды из лаборатории телепортации придумали, как осуществлять доставку товаров на межгалактическом уровне:
для этого нужно положить товар в K K-мерную коробку (представляющую собой гиперпрямоугольник) и разместить саму коробку в специальном устройстве — Телепортаторе.
Технология всё ещё дорабатывается, и параметры коробок, которые лаборатория телепортации научилась производить, ограничены.

Для хранения K K-мерных коробок используется оборудованное помещение — киберсклад, в котором задан ортогональный базис векторов.
Коробку на киберскладе можно разместить только так, что каждое ребро коробки параллельно какому-то из базисных векторов.

Чтобы оптимизировать пространство для хранения, было предложено укладывать коробки друг в друга по принципу матрёшки.
Одну коробку можно поместить в другую, если существует способ повернуть коробки так (при этом в результате поворота рёбра
должны оказаться параллельными базисным векторам), что любое измерение внутренней коробки строго меньше соответствующего измерения внешней коробки.

Задачу по составлению максимальной матрёшки из предложенного набора коробок поручили Вам.
Так как в ближайшее время лаборатория телепортации будет дорабатывать технологию для передачи бананов и лавашей,
Вам необходимо предоставить только конечный результат вычислений по каждому из десяти наборов данных.

== Формат ввода

Команда телепортации предоставила десять наборов данных, описывающих коробки.

В каждом наборе в первой строке находятся натуральные числа N ≤ 10^6^, 2 ≤ K ≤ 20 и A ≤ 10^6 — количество коробок,
размерность пространства, в котором находятся коробки этого набора, и максимальная возможная длина ребра коробки в наборе.

В следующих N строках находятся по K натуральных чисел, каждое из которых не больше A, описывающих измерения коробок.

== Формат вывода

Необходимо для каждого набора данных вывести длину и состав коробочной матрёшки максимальной длины.
На проверку следует отправить единственный файл — по две строки на каждый набор данных.
В первой строке пары — количество коробок в матрёшке, во второй — те коробки, которые эту матрёшку образуют — от внутренней к внешней.

За корректную матрёшку максимальной длины для конкретного набора данных Вы получите 10 баллов.
Если подходит несколько коробочных матрёшек - выведите любую

== Примечания

Пусть лаборатория выдала два файла, содержащих:

`1.in`
[source]
----
3 2 5
2 2
1 1
3 3
----

`2.in`
[source]
----
6 3 10
1 4 7
2 3 6
8 2 5
1 3 2
8 6 9
4 5 3
----

Тогда файл с ответом будет выглядеть так:

`ans.out`
[source]
----
3
2 1 3
3
4 6 5
----