= D. Макс и синтез аминокислот

Макс разрабатывает новую вакцину,
которая позволит защитить людей сразу от нескольких опасных болезней.
Для этого Максу нужно синтезировать N различных определенных аминокислот.

Аминокислоты состоят из оснований:
аденина (A),
цитозина (C),
гуанина (G) и
тимина (T);
каждая из интересующих Макса аминокислот состоит из L оснований.
Другими словами, аминокислоты — это строки длины L,
состоящие из символов {A, C, G, T}.

Синтез аминокислоты происходит следующим образом.
Макс должен взять за основу одну из уже имеющихся аминокислот.
Далее за одно действие Макс может заменить один любой символ в аминокислоте
на следующий или предыдущий в циклической последовательности
{A, C, G, T} (например, за один ход можно заменить одно вхождение A на C или на T).

Изначально у Макса есть только одна аминокислота, состоящая из L символов A.
Как только Макс получает одну из N нужных аминокислот,
он добавляет ее к имеющимся и далее может сколько угодно раз использовать ее
в качестве исходной для синтеза новых аминокислот.

Помогите Максу определить, как оптимальнее всего синтезировать аминокислоты,
и найдите минимальное количество действий для получения всех нужных аминокислот.

== Формат ввода
Первая строка содержит целые числа N и L (1≤N≤500, 1≤L≤500) —
количество аминокислот и количество оснований в аминокислотах соответственно.

Следующие N строк описывают аминокислоты.
Каждая из них содержит последовательность S~i~,
состоящую из L символов {A, C, G, T}.
Все аминокислоты различны.

== Формат вывода
Выведите одно целое число — минимальное количество действий,
за которое Макс сможет получить все перечисленные аминокислоты,
начав с аминокислоты, состоящей из L оснований A.

== Пример

[cols=2]
|====
|Ввод
|Вывод

|3 5 +
GCAGT +
ACAGA +
GCAGA
|6

|8 12 +
CGGCCGCAACTC +
GGATGTTTGCTG +
TTGAAACGTACG +
GCTGCGGGGGTC +
AGGTACTCACAA +
ACATATTTCTGG +
GGAGTGGAGGTC +
AACACGTAGCCC
|72
|====