= A. Клетчатая доска

Вася записался на кружок деревообработки.
Уже завтра ему нужно принести первое собственное изделие — шахматную доску.
Но «папа у Васи силен в математике»,
поэтому посоветовал сформулировать задание шире — сделать доску размера n × n
и раскрасить клетки в k цветов.

Определите, можно ли раскрасить клетки доски n × n в k цветов так,
чтобы:

. Количество клеток каждого цвета было равно stem:[\frac{n^2}{k}].
. Никакие две соседние по сторонам клетки не были окрашены в один цвет.

== Формат ввода
В единственной строке записаны два целых числа n и k (1≤n, k≤10).

== Формат вывода
Если раскраску доски, которую предложил папа Васи, получить невозможно,
то выведите в единственной строке значение No,
иначе в первой строке выведите значение Yes,
а в следующих n строках выведите по n целых чисел c~ij~.
c~ij~ (1≤c~ij~≤k) — цвет,
в который Васе следует раскрасить клетку в i-м ряду и j-м столбце.

Если подходящих раскрасок несколько, выведите любую из них.

== Пример

[cols=2]
|====
|Ввод
|Вывод

|8 2
|Yes +
1 2 1 2 1 2 1 2 +
2 1 2 1 2 1 2 1 +
1 2 1 2 1 2 1 2 +
2 1 2 1 2 1 2 1 +
1 2 1 2 1 2 1 2 +
2 1 2 1 2 1 2 1 +
1 2 1 2 1 2 1 2 +
2 1 2 1 2 1 2 1

|2 1
|No

|3 3
|Yes +
1 2 1 +
2 3 2 +
3 1 3

|1 3
|No

|5 3
|No

|====