= A. Статистика по полям

Дан JSON, описывающий корневое дерево метаинформации некоторой файловой системы.
Это дерево содержит больше одного узла, каждое ребро этого дерева помечено строковой меткой, а в каждом листе записано значение (оно может быть строкой, числом или null).

Соответствующий дереву JSON определяется следующим образом:

. значение листа дерева представляется соответствующим JSON-значением;
. внутренний узел дерева представляется JSON-словарём, у которого ключами являются метки рёбер от узла к дочерним узлам, а значениями являются соответствующие JSON-представления дочерних узлов.

Путём к листу является цепочка всех меток на пути от корня до листа, перечисленных через точку.

JSON-представление выглядит следующим образом.

[source,json]
----
{
  "a": {
    "a": {
      "b": 123,
      "c": "value"
    }
  },
  "b": {
    "a": {
      "b": 456,
      "c": null
    }
  }
}
----

На вход поступают запросы в виде JSON’а со следующими полями:

. path — строка, состоящая из меток, соединенных точкой;
. count — неотрицательное целое число.

В path ровно одна метка является звёздочкой.
Ответом на запрос является JSON-словарь, содержащий единственное поле result.
Значение этого поля определяется следующим образом:

. в дереве определяются все листья, пути до которых можно получить, заменив звёздочку из поля path в запросе на непустую цепочку других меток;
. создаётся список L со значениями в этих листьях;
. из L удаляются все null-значения;
. если среди оставшихся значений в L есть и строки, и числа, то значение поля result равно null;
. в противном случае оставшиеся значения L сортируются (числа сортируются по невозрастанию, а строки — по обратному лексикографическому порядку), причём если значений больше, чем count , то в L остаются только первые count значений;
. тогда значение поля result равно L.

== Формат ввода

В первой строке входных данных содержится JSON-представление дерева.
В дереве не более 10000 узлов.
И метки, и строковые значения в листьях — это непустые строки длиною до 20 , состоящие из строчных букв латинского алфавита и цифр.
Числовые значения в листьях — это неотрициательные целые числа, не превосходящие 10^9.
Во второй строке указано число запросов q (1 ≤ q ≤ 100).

В следующих q строках указаны JSON-запросы.
На метки в path такие же ограничения, как и для меток на рёбрах дерева, за исключением одной метки, которая является звёздочкой (*).
Количество меток в path от 2 до 20 , значение count от 1 до 100.

== Формат вывода

Выведите q строк, где i-я строка является ответом на i-ый запрос.

== Пример

[cols=2]
|===
|Ввод
|Вывод

|
{"a": {"a": {"b": 123, "c": "value"}}, "b": {"a": {"b": 456, "c": null}}} +
5 +
{"path": "\*.b", "count": 2} +
{"path": "a.a.\*", "count": 5} +
{"path": "b.\*.c", "count": 1} +
{"path": "a.b.c.\*", "count": 5} +
{"path": "a.a.\*.b", "count": 2}

|{"result":[456,123]} +
{"result":null} +
{"result":[]} +
{"result":[]} +
{"result":[]}
|===